name: basic-web-app

on:
  push:
    branches:
      - main

jobs:
  query_tests:
    runs-on: ubuntu-latest
    name: query_tests

    steps:
      - uses: actions/checkout@v3

      - uses: bahmutov/npm-install@v1

      - run: npm run lint

      - run: npm run test